-- CREACION DE TABLA TEMPORAL DE VOTACIONES
CREATE TEMPORARY TABLE bd1_proyecto1.temp_votaciones (
	id_voto INTEGER NOT NULL,
	id_candidato INTEGER NOT NULL,
    dpi BIGINT NOT NULL,
    mesa_id INTEGER NOT NULL,
    fecha_hora DATETIME NOT NULL
);

-- CREACION DE TABLA TEMPORAL PARTIDO
CREATE TEMPORARY TABLE bd1_proyecto1.temp_partido (
	id INTEGER NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	siglas VARCHAR(15) NOT NULL,
	fundacion DATE NOT NULL
);

-- CREACION DE TABLA TEMPORAL MESA
CREATE TEMPORARY TABLE bd1_proyecto1.temp_mesa (
	id INTEGER NOT NULL,
	departamento_id INTEGER NOT NULL
);

-- CREACION DE TABLA TEMPORAL DEPARTAMENTO
CREATE TEMPORARY TABLE bd1_proyecto1.temp_departamento (
	id INTEGER NOT NULL,
	nombre VARCHAR(50) NOT NULL
);

-- CREACION DE TABLA TEMPORAL CIUDADANO
CREATE TEMPORARY TABLE bd1_proyecto1.temp_ciudadano (
	dpi BIGINT NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    telefono VARCHAR(10) NOT NULL,
	edad INTEGER NOT NULL,
    genero VARCHAR(1) NOT NULL
);

-- CREACION DE TABLA TEMPORAL CARGO
CREATE TEMPORARY TABLE bd1_proyecto1.temp_cargo (
	id INTEGER NOT NULL,
	cargo VARCHAR(50) NOT NULL
);

-- CREACION DE TABLA TEMPORAL CANDIDATO
CREATE TEMPORARY TABLE bd1_proyecto1.temp_candidato (
	id INTEGER NOT NULL,
	nombres VARCHAR(50) NOT NULL,
	fecha_nacimiento DATE NOT NULL,
    partido_id INTEGER NOT NULL,
    cargo_id INTEGER NOT NULL
);